# Simulation 1 varicelle

In [431]:
import numpy as np
import matplotlib.pyplot as plt
import random
import copy

### Initialisation du système

In [432]:
eleves = np.zeros([5,5])
print (eleves)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


**On a une matrice de 25 éléments représentant une classe de 25 élèves. Les 0 désignent les élèves sains**

### Simulation

**Le modèle est simple**: Un élève malade est représenté par l'élément 1. 
    On va d'abord prendre un élève au hasard et dire qu'il est malade. A chaque itération un autre tombe malade au hasard. On admet que cela est causé par la rencontre entre l'élève initalement malade et un autre élève quelconque de la classe. Dans la simulation, on se rend compte que parfois le nombre de malades ne change pas : c'est parce que la position d'un enfant déjà malade a été tirée. On admet alors qu'à cette itération il n'y a pas eu d'intéractions entre un malade et un sain.

In [433]:
def positions():
    position=[]#liste de positions
    
    for i in range(5):
        for j in range(5):
            position.append([i,j])
            np.random.shuffle(position)
    return (position[0])
    
    

In [434]:
np.random.randint(5,size=2)

array([3, 4])

In [435]:
positions()

[2, 3]

In [436]:
def premier_etat():
    position=positions()
    k=position[0]
    l=position[1]
    eleves[k][l]=1
    return (eleves, position)


In [437]:
premier_etat()


(array([[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]), [1, 0])

Dans cet exemple, au bout de la 50ème itération, **20 enfants sur 25** ont attrapé la varicelle.

In [438]:
def simulation():
    x=0
    while (x<25):
        new_premier_etat=premier_etat()
        print(new_premier_etat)
        x+=1
    return(new_premier_etat)
        

In [439]:
simulation()

(array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]]), [3, 4])
(array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]]), [1, 2])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 1])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.]]), [4, 2])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.]]), [3, 2])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.

(array([[ 0.,  1.,  1.,  1.,  0.],
        [ 1.,  1.,  1.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  1.,  1.,  1.],
        [ 0.,  0.,  1.,  1.,  0.]]), [1, 4])

In [440]:
matrice = np.zeros([7,7])
print (matrice)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [441]:
matrice = np.ones([7,7])
print (matrice)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [442]:
def pos():
    position=[]#liste de positions
    
    for i in range(7):
        for j in range(7):
            position.append([i,j])
            np.random.shuffle(position)
    return (position)

In [443]:
pos()


[[5, 3],
 [5, 2],
 [4, 3],
 [3, 2],
 [6, 0],
 [5, 6],
 [1, 0],
 [1, 4],
 [5, 1],
 [0, 6],
 [1, 1],
 [4, 4],
 [6, 4],
 [6, 2],
 [2, 4],
 [4, 2],
 [2, 0],
 [3, 6],
 [1, 5],
 [1, 6],
 [5, 0],
 [2, 3],
 [0, 4],
 [2, 2],
 [6, 5],
 [2, 6],
 [0, 2],
 [3, 4],
 [0, 5],
 [6, 3],
 [0, 1],
 [4, 6],
 [0, 0],
 [0, 3],
 [3, 5],
 [3, 0],
 [2, 1],
 [4, 5],
 [1, 3],
 [3, 1],
 [4, 1],
 [6, 6],
 [5, 4],
 [4, 0],
 [5, 5],
 [1, 2],
 [6, 1],
 [2, 5],
 [3, 3]]

In [444]:
def cases_vides():
    vide=[]
    position=pos()
    i=0
    while (i<24):
        vide.append(position[i])
        i=i+1
        
    return(vide)
    



In [445]:
cases_vides()

[[4, 4],
 [0, 5],
 [6, 3],
 [2, 5],
 [2, 1],
 [4, 3],
 [4, 6],
 [1, 6],
 [6, 2],
 [5, 5],
 [6, 4],
 [4, 5],
 [2, 4],
 [0, 0],
 [2, 6],
 [4, 1],
 [4, 2],
 [6, 5],
 [5, 3],
 [6, 6],
 [6, 0],
 [0, 3],
 [3, 1],
 [3, 6]]

In [446]:
len(cases_vides())

24

In [447]:
def matrice_cases_vides():
    cases=cases_vides()
    for k in cases:
        [a,b]=k
        matrice[a][b]=0
        
    return(matrice)

        

In [448]:
matrice_cases_vides()

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.]])

In [449]:
x=np.where(matrice == 1)
x

(array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6,
        6, 6]),
 array([1, 3, 5, 0, 2, 3, 4, 6, 1, 2, 3, 5, 0, 5, 6, 4, 6, 2, 4, 6, 1, 3, 4,
        5, 6]))

In [450]:
posi_1=[]
posi_1 = sum(map(list, zip(x[0], x[1])), [])

print (posi_1)

[0, 1, 0, 3, 0, 5, 1, 0, 1, 2, 1, 3, 1, 4, 1, 6, 2, 1, 2, 2, 2, 3, 2, 5, 3, 0, 3, 5, 3, 6, 4, 4, 4, 6, 5, 2, 5, 4, 5, 6, 6, 1, 6, 3, 6, 4, 6, 5, 6, 6]


In [451]:
deux=[]
i=0
j=1
while i<50 and j<50:
        deux.append((posi_1[i],posi_1[j]))
        
        i+=2
        j+=2
print (deux)

[(0, 1), (0, 3), (0, 5), (1, 0), (1, 2), (1, 3), (1, 4), (1, 6), (2, 1), (2, 2), (2, 3), (2, 5), (3, 0), (3, 5), (3, 6), (4, 4), (4, 6), (5, 2), (5, 4), (5, 6), (6, 1), (6, 3), (6, 4), (6, 5), (6, 6)]


In [452]:
matrice

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.]])

In [453]:
matrice2=np.copy(matrice)
matrice2

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.]])

In [454]:
deux_r=random.choice(deux)
i=deux_r[0]
j=deux_r[1]

matrice2[i][j]=2
matrice2

array([[ 0.,  2.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.]])

In [473]:
def voisin():
    elements=[]
    voisins={}
    for i in range(7):
        for j in range(7):
            elements.append((i,j))
            if (i,j)==(0,0):
                voisins[(i,j)]=[(i+1,j),(i,j+1)]
            elif (i,j)==(0,6):
                voisins[(i,j)]=[(i,j-1),(i+1,j)]
            elif (i,j)==(6,0):
                voisins[(i,j)]=[(i-1,j),(i,j+1)]
            elif (i,j)==(6,6):
                voisins[(i,j)]=[(i,j-1),(i-1,j)]
                
            elif (i==0 and j>=1 and j<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i,j-1)]
                
                
            elif (i==6 and j>=1 and j<=5):
                voisins[(i,j)]=[(i-1,j),(i,j+1),(i,j-1)]
                
                
            elif (j==0 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i-1,j)]
            
            elif (j==6 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1)]
            else:
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1),(i,j+1)]
    return(voisins)
    

In [474]:
voisin()

{(0, 0): [(1, 0), (0, 1)],
 (0, 1): [(1, 1), (0, 2), (0, 0)],
 (0, 2): [(1, 2), (0, 3), (0, 1)],
 (0, 3): [(1, 3), (0, 4), (0, 2)],
 (0, 4): [(1, 4), (0, 5), (0, 3)],
 (0, 5): [(1, 5), (0, 6), (0, 4)],
 (0, 6): [(0, 5), (1, 6)],
 (1, 0): [(2, 0), (1, 1), (0, 0)],
 (1, 1): [(2, 1), (0, 1), (1, 0), (1, 2)],
 (1, 2): [(2, 2), (0, 2), (1, 1), (1, 3)],
 (1, 3): [(2, 3), (0, 3), (1, 2), (1, 4)],
 (1, 4): [(2, 4), (0, 4), (1, 3), (1, 5)],
 (1, 5): [(2, 5), (0, 5), (1, 4), (1, 6)],
 (1, 6): [(2, 6), (0, 6), (1, 5)],
 (2, 0): [(3, 0), (2, 1), (1, 0)],
 (2, 1): [(3, 1), (1, 1), (2, 0), (2, 2)],
 (2, 2): [(3, 2), (1, 2), (2, 1), (2, 3)],
 (2, 3): [(3, 3), (1, 3), (2, 2), (2, 4)],
 (2, 4): [(3, 4), (1, 4), (2, 3), (2, 5)],
 (2, 5): [(3, 5), (1, 5), (2, 4), (2, 6)],
 (2, 6): [(3, 6), (1, 6), (2, 5)],
 (3, 0): [(4, 0), (3, 1), (2, 0)],
 (3, 1): [(4, 1), (2, 1), (3, 0), (3, 2)],
 (3, 2): [(4, 2), (2, 2), (3, 1), (3, 3)],
 (3, 3): [(4, 3), (2, 3), (3, 2), (3, 4)],
 (3, 4): [(4, 4), (2, 4), (3, 3), (3,

In [ ]:
def rencontre():
    for i in range(7):
        for j in range(7):
            if ((posi_1[i][j])!=0):
               
                
                
                
                