# Simulation 1 varicelle

In [2091]:
import numpy as np
import matplotlib.pyplot as plt
import random
import copy

### Initialisation du système

In [2092]:
eleves = np.zeros([5,5])
print (eleves)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


**On a une matrice de 25 éléments représentant une classe de 25 élèves. Les 0 désignent les élèves sains**

### Simulation

**Le modèle est simple**: Un élève malade est représenté par l'élément 1. 
    On va d'abord prendre un élève au hasard et dire qu'il est malade. A chaque itération un autre tombe malade au hasard. On admet que cela est causé par la rencontre entre l'élève initalement malade et un autre élève quelconque de la classe. Dans la simulation, on se rend compte que parfois le nombre de malades ne change pas : c'est parce que la position d'un enfant déjà malade a été tirée. On admet alors qu'à cette itération il n'y a pas eu d'intéractions entre un malade et un sain.

In [2093]:
def positions():
    position=[]#liste de positions
    
    for i in range(5):
        for j in range(5):
            position.append([i,j])
            np.random.shuffle(position)
    return (position[0])
    
    

In [2094]:
np.random.randint(5,size=2)

array([0, 0])

In [2095]:
positions()

[4, 3]

In [2096]:
def premier_etat():
    position=positions()
    k=position[0]
    l=position[1]
    eleves[k][l]=1
    return (eleves, position)


In [2097]:
premier_etat()


(array([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]), [2, 2])

Dans cet exemple, au bout de la 50ème itération, **20 enfants sur 25** ont attrapé la varicelle.

In [2098]:
def simulation():
    x=0
    while (x<25):
        new_premier_etat=premier_etat()
        print(new_premier_etat)
        x+=1
    return(new_premier_etat)
        

In [2099]:
simulation()

(array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [3, 3])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 1])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [1, 0])
(array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [3, 0])
(array([[ 0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 3])
(array([[ 0.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.

(array([[ 0.,  1.,  0.,  1.,  1.],
        [ 1.,  1.,  0.,  1.,  1.],
        [ 0.,  0.,  1.,  0.,  1.],
        [ 1.,  0.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  0.]]), [0, 1])

In [2100]:
matrice = np.zeros([7,7])
print (matrice)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [2101]:
matrice = np.ones([7,7])
print (matrice)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [2102]:
def pos():
    position=[]#liste de positions
    
    for i in range(7):
        for j in range(7):
            position.append([i,j])
            np.random.shuffle(position)
    return (position)

In [2103]:
pos()


[[6, 5],
 [0, 6],
 [5, 0],
 [5, 6],
 [5, 4],
 [3, 5],
 [5, 2],
 [2, 1],
 [4, 2],
 [1, 1],
 [0, 0],
 [3, 3],
 [5, 5],
 [3, 0],
 [2, 4],
 [0, 5],
 [1, 4],
 [1, 5],
 [5, 3],
 [0, 4],
 [4, 6],
 [3, 6],
 [5, 1],
 [1, 3],
 [0, 3],
 [6, 6],
 [0, 1],
 [6, 0],
 [2, 2],
 [4, 1],
 [1, 2],
 [1, 0],
 [4, 4],
 [2, 6],
 [6, 1],
 [0, 2],
 [6, 4],
 [2, 0],
 [1, 6],
 [2, 3],
 [6, 3],
 [3, 2],
 [4, 3],
 [3, 1],
 [6, 2],
 [2, 5],
 [4, 5],
 [3, 4],
 [4, 0]]

In [2104]:
def cases_vides():
    vide=[]
    position=pos()
    i=0
    while (i<24):
        vide.append(position[i])
        i=i+1
        
    return(vide)
    



In [2105]:
cases_vides()

[[1, 6],
 [6, 5],
 [0, 2],
 [4, 5],
 [1, 1],
 [1, 4],
 [3, 2],
 [2, 0],
 [5, 5],
 [4, 1],
 [6, 0],
 [5, 0],
 [0, 1],
 [5, 2],
 [4, 6],
 [0, 4],
 [2, 2],
 [3, 4],
 [0, 5],
 [6, 4],
 [2, 5],
 [5, 1],
 [5, 4],
 [2, 4]]

In [2106]:
len(cases_vides())

24

In [2107]:
def matrice_cases_vides():
    cases=cases_vides()
    for k in cases:
        [a,b]=k
        matrice[a][b]=0
        
    return(matrice)

        

In [2108]:
matrice_cases_vides()

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [2109]:
x=np.where(matrice == 1)
x

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 6, 6,
        6, 6]),
 array([0, 1, 2, 4, 5, 1, 2, 5, 6, 0, 1, 2, 4, 5, 6, 4, 2, 3, 2, 3, 5, 0, 1,
        3, 5]))

In [2110]:
posi_1=[]
posi_1 = sum(map(list, zip(x[0], x[1])), [])

print (posi_1)

[0, 0, 0, 1, 0, 2, 0, 4, 0, 5, 1, 1, 1, 2, 1, 5, 1, 6, 2, 0, 2, 1, 2, 2, 2, 4, 2, 5, 2, 6, 3, 4, 4, 2, 4, 3, 5, 2, 5, 3, 5, 5, 6, 0, 6, 1, 6, 3, 6, 5]


In [2111]:
deux=[]
i=0
j=1
while i<50 and j<50:
        deux.append((posi_1[i],posi_1[j]))
        
        i+=2
        j+=2
print (deux)

[(0, 0), (0, 1), (0, 2), (0, 4), (0, 5), (1, 1), (1, 2), (1, 5), (1, 6), (2, 0), (2, 1), (2, 2), (2, 4), (2, 5), (2, 6), (3, 4), (4, 2), (4, 3), (5, 2), (5, 3), (5, 5), (6, 0), (6, 1), (6, 3), (6, 5)]


In [2112]:
matrice

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [2113]:
matrice2=np.copy(matrice)
matrice2

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [2114]:
deux_r=random.choice(deux)
i=deux_r[0]
j=deux_r[1]

matrice2[i][j]=2
matrice2

array([[ 2.,  1.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [2115]:
def voisin():
    elements=[]
    voisins={}
    for i in range(7):
        for j in range(7):
            elements.append((i,j))
            if (i,j)==(0,0):
                voisins[(i,j)]=[(i+1,j),(i,j+1)]
            elif (i,j)==(0,6):
                voisins[(i,j)]=[(i,j-1),(i+1,j)]
            elif (i,j)==(6,0):
                voisins[(i,j)]=[(i-1,j),(i,j+1)]
            elif (i,j)==(6,6):
                voisins[(i,j)]=[(i,j-1),(i-1,j)]
                
            elif (i==0 and j>=1 and j<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i,j-1)]
                
                
            elif (i==6 and j>=1 and j<=5):
                voisins[(i,j)]=[(i-1,j),(i,j+1),(i,j-1)]
                
                
            elif (j==0 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i-1,j)]
            
            elif (j==6 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1)]
            else:
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1),(i,j+1)]
    return(voisins)
    

In [2116]:
voisin()

{(0, 0): [(1, 0), (0, 1)],
 (0, 1): [(1, 1), (0, 2), (0, 0)],
 (0, 2): [(1, 2), (0, 3), (0, 1)],
 (0, 3): [(1, 3), (0, 4), (0, 2)],
 (0, 4): [(1, 4), (0, 5), (0, 3)],
 (0, 5): [(1, 5), (0, 6), (0, 4)],
 (0, 6): [(0, 5), (1, 6)],
 (1, 0): [(2, 0), (1, 1), (0, 0)],
 (1, 1): [(2, 1), (0, 1), (1, 0), (1, 2)],
 (1, 2): [(2, 2), (0, 2), (1, 1), (1, 3)],
 (1, 3): [(2, 3), (0, 3), (1, 2), (1, 4)],
 (1, 4): [(2, 4), (0, 4), (1, 3), (1, 5)],
 (1, 5): [(2, 5), (0, 5), (1, 4), (1, 6)],
 (1, 6): [(2, 6), (0, 6), (1, 5)],
 (2, 0): [(3, 0), (2, 1), (1, 0)],
 (2, 1): [(3, 1), (1, 1), (2, 0), (2, 2)],
 (2, 2): [(3, 2), (1, 2), (2, 1), (2, 3)],
 (2, 3): [(3, 3), (1, 3), (2, 2), (2, 4)],
 (2, 4): [(3, 4), (1, 4), (2, 3), (2, 5)],
 (2, 5): [(3, 5), (1, 5), (2, 4), (2, 6)],
 (2, 6): [(3, 6), (1, 6), (2, 5)],
 (3, 0): [(4, 0), (3, 1), (2, 0)],
 (3, 1): [(4, 1), (2, 1), (3, 0), (3, 2)],
 (3, 2): [(4, 2), (2, 2), (3, 1), (3, 3)],
 (3, 3): [(4, 3), (2, 3), (3, 2), (3, 4)],
 (3, 4): [(4, 4), (2, 4), (3, 3), (3,

In [2117]:
def deplacement():
    print(matrice2)
    voisina=voisin()
    t=0
    while t<2:
        for i in voisina:
            x,y=i
            for j in voisina[i]:
                a,b=j
                if ((matrice2[x][y]!=0) and (matrice2[a][b]==0)):
                    e=matrice2[a][b]
                    e2=matrice2[x][y]
                    matrice2[a][b]=e2
                    matrice2[x][y]=e
                if(matrice2[x][y]==2 and matrice2[a][b]==1):
                    matrice2[a][b]=2

        t=t+1
    return (matrice2)
    
        
            
                
    

In [2118]:
deplacement()

[[ 2.  1.  1.  0.  1.  1.  0.]
 [ 0.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  1.  0.]
 [ 1.  1.  0.  1.  0.  1.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  1.,  0.],
       [ 2.,  2.,  2.,  1.,  1.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  1.,  1.,  0.],
       [ 2.,  2.,  0.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [2119]:
def contamination():
    deplacements=deplacement()
    
    for i in deplacements:
        if((matrice2[x][y]==2 and matrice2[a][b]==1))or((matrice2[x][y]==1 and matrice2[a][b]==2)):
            matrice2[a][b]=2
            matrice2[x][y]=2
            
    print(deplacements)
                   
    
    

In [2120]:
contamination()

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  1.  0.]
 [ 2.  2.  2.  1.  1.  0.  0.]
 [ 0.  2.  0.  0.  1.  1.  0.]
 [ 2.  2.  0.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


NameError: name 'y' is not defined