# Simulation 1 varicelle

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Initialisation du système

In [3]:
eleves = np.zeros([5,5])
print (eleves)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


**On a une matrice de 25 éléments représentant une classe de 25 élèves. Les 0 désignent les élèves sains**

### Simulation

**Le modèle est simple**: Un élève malade est représenté par l'élément 1. 
    On va d'abord prendre un élève au hasard et dire qu'il est malade. A chaque itération un autre tombe malade au hasard. On admet que cela est causé par la rencontre entre l'élève initalement malade et un autre élève quelconque de la classe. Dans la simulation, on se rend compte que parfois le nombre de malades ne change pas : c'est parce que la position d'un enfant déjà malade a été tirée. On admet alors qu'à cette itération il n'y a pas eu d'intéractions entre un malade et un sain.

In [4]:
def positions():
    position=[]#liste de positions
    
    for i in range(5):
        for j in range(5):
            position.append([i,j])
            np.random.shuffle(position)
    return (position[0])
    
    

In [5]:
np.random.randint(5,size=2)

array([0, 1])

In [6]:
positions()

[3, 0]

In [7]:
def premier_etat():
    position=positions()
    k=position[0]
    l=position[1]
    eleves[k][l]=1
    return (eleves, position)


In [8]:
premier_etat()


(array([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]), [2, 3])

Dans cet exemple, au bout de la 50ème itération, **20 enfants sur 25** ont attrapé la varicelle.

In [9]:
def simulation():
    x=0
    while (x<25):
        new_premier_etat=premier_etat()
        print(new_premier_etat)
        x+=1
    return(new_premier_etat)
        

In [10]:
simulation()

(array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 4])
(array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 4])
(array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 4])
(array([[ 0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [0, 3])
(array([[ 0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]), [3, 0])
(array([[ 0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.

(array([[ 0.,  1.,  0.,  1.,  1.],
        [ 1.,  0.,  0.,  1.,  1.],
        [ 0.,  0.,  0.,  1.,  1.],
        [ 1.,  1.,  0.,  0.,  1.],
        [ 1.,  1.,  0.,  1.,  0.]]), [1, 3])

In [11]:
matrice = np.zeros([7,7])
print (matrice)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
matrice = np.zeros([7,7])
print (matrice)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [14]:
positions()


[0, 4]

In [15]:
    def cases_vides():
        P=[]
        x=0
        position=positions()
        for p in position:
             if (p not in P and while(x<=24)):
                P.append(p)
                x=x+1
        return P



SyntaxError: invalid syntax (<ipython-input-15-8954d6d57862>, line 6)

In [16]:
cases_vides()

NameError: name 'cases_vides' is not defined

In [17]:
len(cases_vides())

NameError: name 'cases_vides' is not defined