In [644]:
import numpy as np
import matplotlib.pyplot as plt
import random
import copy
%matplotlib notebook

[[ 1.  0.  1.  0.  1.  1.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  2.  1.  0.]
 [ 1.  1.  0.  1.  1.  0.  1.]
 [ 1.  0.  0.  0.  1.  1.  0.]]
[(1, 2), (1, 4)]
[(1, 2), (1, 4)]
[(1, 2), (1, 4)]
[(1, 2), (1, 4)]
[(6, 5), (5, 6)]
[(6, 5), (5, 6)]
[(3, 1)]
On a bougé de (3, 0) vers (4, 0)
[(4, 0), (3, 1)]
[(4, 0), (3, 1)]
[(6, 4), (5, 3)]
[(6, 4), (5, 3)]
[(6, 4), (5, 3)]
[(6, 4), (5, 3)]
On a bougé de (5, 4) vers (5, 5)
[(3, 1), (2, 2)]
[(3, 1), (2, 2)]
On a bougé de (2, 1) vers (1, 1)
[(3, 1), (1, 1), (2, 2)]
[(3, 1), (1, 1), (2, 2)]
[]
[]
[]
[(0, 6)]
[(0, 6)]
[(0, 6)]
[(4, 1), (5, 0)]
On a bougé de (5, 1) vers (6, 1)
[(6, 1), (4, 1), (5, 0)]
[(6, 1), (4, 1), (5, 0)]
[(6, 1), (4, 1), (5, 0)]
[(2, 4)]
[(2, 4)]
[(2, 4)]
[(2, 4)]
[(0, 4), (0, 2)]
[(0, 4), (0, 2)]
[(0, 4), (0, 2)]
[(5, 0), (4, 1)]
[(5, 0), (4, 1)]
[(5, 0), (4, 1)]
On a bougé de (4, 0) vers (3, 0)
[(2, 2), (0, 2), (1, 1)]
[(2, 2), (0, 2), (1, 1)]
[(2,

In [645]:
matrice = np.ones([7,7])
print (matrice)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [646]:
def pos():
    position=[]#liste de positions
    
    for i in range(7):
        for j in range(7):
            position.append([i,j])
            np.random.shuffle(position)
    return (position)

In [647]:
def cases_vides():
    vide=[]
    position=pos()
    i=0
    while (i<24):
        vide.append(position[i])
        i=i+1
        
    return(vide)
    

In [648]:
cases_vides()

[[1, 2],
 [6, 1],
 [2, 2],
 [2, 6],
 [5, 4],
 [4, 5],
 [4, 2],
 [5, 2],
 [6, 0],
 [5, 6],
 [2, 4],
 [6, 2],
 [6, 5],
 [6, 4],
 [0, 3],
 [3, 4],
 [1, 3],
 [0, 4],
 [0, 2],
 [2, 0],
 [2, 1],
 [1, 0],
 [3, 3],
 [5, 0]]

In [649]:
def matrice_cases_vides():
    cases=cases_vides()
    for k in cases:
        [a,b]=k
        matrice[a][b]=0
        
    return(matrice)


In [650]:
matrice_cases_vides()

array([[ 0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.]])

In [651]:
x=np.where(matrice == 1)
x

(array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6,
        6, 6]),
 array([2, 4, 0, 3, 4, 5, 6, 2, 5, 3, 4, 5, 2, 3, 5, 0, 2, 3, 4, 5, 6, 1, 2,
        3, 5]))

In [652]:
posi_1=[]
posi_1 = sum(map(list, zip(x[0], x[1])), [])

print (posi_1)

[0, 2, 0, 4, 1, 0, 1, 3, 1, 4, 1, 5, 1, 6, 2, 2, 2, 5, 3, 3, 3, 4, 3, 5, 4, 2, 4, 3, 4, 5, 5, 0, 5, 2, 5, 3, 5, 4, 5, 5, 5, 6, 6, 1, 6, 2, 6, 3, 6, 5]


In [653]:
deux=[]
i=0
j=1
while i<50 and j<50:
        deux.append((posi_1[i],posi_1[j]))
        
        i+=2
        j+=2
print (deux)

[(0, 2), (0, 4), (1, 0), (1, 3), (1, 4), (1, 5), (1, 6), (2, 2), (2, 5), (3, 3), (3, 4), (3, 5), (4, 2), (4, 3), (4, 5), (5, 0), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1), (6, 2), (6, 3), (6, 5)]


In [654]:
matrice2=np.copy(matrice)
matrice2

array([[ 0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.]])

In [655]:
deux_r=random.choice(deux)
i=deux_r[0]
j=deux_r[1]

matrice2[i][j]=2
matrice2

array([[ 0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  2.,  1.,  1.,  0.,  1.,  0.]])

In [656]:
def voisin():
    elements=[]
    voisins={}
    for i in range(7):
        for j in range(7):
            elements.append((i,j))
            if (i,j)==(0,0):
                voisins[(i,j)]=[(i+1,j),(i,j+1)]
            elif (i,j)==(0,6):
                voisins[(i,j)]=[(i,j-1),(i+1,j)]
            elif (i,j)==(6,0):
                voisins[(i,j)]=[(i-1,j),(i,j+1)]
            elif (i,j)==(6,6):
                voisins[(i,j)]=[(i,j-1),(i-1,j)]
                
            elif (i==0 and j>=1 and j<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i,j-1)]
                
                
            elif (i==6 and j>=1 and j<=5):
                voisins[(i,j)]=[(i-1,j),(i,j+1),(i,j-1)]
                
                
            elif (j==0 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i,j+1),(i-1,j)]
            
            elif (j==6 and i>=1 and i<=5):
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1)]
            else:
                voisins[(i,j)]=[(i+1,j),(i-1,j),(i,j-1),(i,j+1)]
    return(voisins)

In [657]:
voisin()

{(0, 0): [(1, 0), (0, 1)],
 (0, 1): [(1, 1), (0, 2), (0, 0)],
 (0, 2): [(1, 2), (0, 3), (0, 1)],
 (0, 3): [(1, 3), (0, 4), (0, 2)],
 (0, 4): [(1, 4), (0, 5), (0, 3)],
 (0, 5): [(1, 5), (0, 6), (0, 4)],
 (0, 6): [(0, 5), (1, 6)],
 (1, 0): [(2, 0), (1, 1), (0, 0)],
 (1, 1): [(2, 1), (0, 1), (1, 0), (1, 2)],
 (1, 2): [(2, 2), (0, 2), (1, 1), (1, 3)],
 (1, 3): [(2, 3), (0, 3), (1, 2), (1, 4)],
 (1, 4): [(2, 4), (0, 4), (1, 3), (1, 5)],
 (1, 5): [(2, 5), (0, 5), (1, 4), (1, 6)],
 (1, 6): [(2, 6), (0, 6), (1, 5)],
 (2, 0): [(3, 0), (2, 1), (1, 0)],
 (2, 1): [(3, 1), (1, 1), (2, 0), (2, 2)],
 (2, 2): [(3, 2), (1, 2), (2, 1), (2, 3)],
 (2, 3): [(3, 3), (1, 3), (2, 2), (2, 4)],
 (2, 4): [(3, 4), (1, 4), (2, 3), (2, 5)],
 (2, 5): [(3, 5), (1, 5), (2, 4), (2, 6)],
 (2, 6): [(3, 6), (1, 6), (2, 5)],
 (3, 0): [(4, 0), (3, 1), (2, 0)],
 (3, 1): [(4, 1), (2, 1), (3, 0), (3, 2)],
 (3, 2): [(4, 2), (2, 2), (3, 1), (3, 3)],
 (3, 3): [(4, 3), (2, 3), (3, 2), (3, 4)],
 (3, 4): [(4, 4), (2, 4), (3, 3), (3,

In [658]:
def vraideplacement(matrice2):
    matrice2= initialisation_matrice()

    print(matrice2)
    voisina=voisin()
    t=0
    liste=[]
    while t<10:
        for i in voisina:
            x,y=i   
            for j in voisina[i]:
                a,b=j
                enfants_voisins = [pos for pos in voisina[i] if matrice2[pos] == 1]
                print(enfants_voisins)
                if matrice2[x,y] == 2:
                    print(" {} le malade".format((x,y)))
                if ((matrice2[x][y]!=0) and (matrice2[a][b]==0)):
                    e=matrice2[a][b]
                    e2=matrice2[x][y]
                    matrice2[a][b]=e2
                    matrice2[x][y]=e
                    print("On a bougé de {} vers {}".format((x,y), (a,b)))
                if len(enfants_voisins) > 0 and matrice2[x,y] == 2:
                    choix=random.choice(enfants_voisins)
                    matrice2[choix]=2
                    print("On a contaminé {}".format(choix))

                liste.append(matrice2.copy())
                liste.append([(x,y),(a,b)])

        t=t+1
    return liste
    


In [659]:
v = voisin()

In [660]:
vraideplacement(matrice2)

[[ 0.  1.  0.  0.  0.  1.  1.]
 [ 1.  1.  1.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.]
 [ 1.  0.  1.  1.  1.  1.  0.]
 [ 0.  0.  1.  0.  1.  1.  0.]
 [ 1.  2.  1.  1.  0.  0.  1.]
 [ 0.  0.  1.  1.  0.  0.  0.]]
[(2, 3), (1, 2), (1, 4)]
[(2, 3), (1, 2), (1, 4)]
[(2, 3), (1, 2), (1, 4)]
[(2, 3), (1, 2), (1, 4)]
[(5, 6)]
[(5, 6)]
[]
On a bougé de (3, 0) vers (4, 0)
[(4, 0)]
[(4, 0)]
[(4, 4), (5, 3)]
[(4, 4), (5, 3)]
[(4, 4), (5, 3)]
[(4, 4), (5, 3)]
[(1, 1)]
[(1, 1)]
[(1, 1)]
[(1, 1)]
[(1, 6)]
[(1, 6)]
[(1, 6)]
[(0, 6)]
On a bougé de (1, 6) vers (2, 6)
[(2, 6), (0, 6)]
[(2, 6), (0, 6)]
[(5, 0), (5, 2)]
 (5, 1) le malade
On a bougé de (5, 1) vers (6, 1)
[(5, 0), (5, 2)]
[(5, 0), (5, 2)]
[(5, 0), (5, 2)]
[(3, 5), (2, 4), (2, 6)]
[(3, 5), (2, 4), (2, 6)]
[(3, 5), (2, 4), (2, 6)]
[(3, 5), (2, 4), (2, 6)]
[]
[]
[]
[(5, 0)]
[(5, 0)]
On a bougé de (4, 0) vers (4, 1)
[(5, 0), (4, 1)]
[(1, 1)]
On a bougé de (1, 2) vers (2, 2)
[(2, 2), (1, 1)]
[(2, 2), (1, 1)]
[(2, 2), (1, 1)]
[(4, 5), (5, 6

[array([[ 0.,  1.,  0.,  0.,  0.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  1.,  1.,  0.,  0.],
        [ 1.,  0.,  1.,  1.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  1.,  1.,  0.],
        [ 1.,  2.,  1.,  1.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  1.,  0.,  0.,  0.]]),
 [(1, 3), (2, 3)],
 array([[ 0.,  1.,  0.,  0.,  0.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  1.,  1.,  0.,  0.],
        [ 1.,  0.,  1.,  1.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  1.,  1.,  0.],
        [ 1.,  2.,  1.,  1.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  1.,  0.,  0.,  0.]]),
 [(1, 3), (0, 3)],
 array([[ 0.,  1.,  0.,  0.,  0.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  1.,  0.,  1.],
        [ 0.,  0.,  0.,  1.,  1.,  0.,  0.],
        [ 1.,  0.,  1.,  1.,  1.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  1.,  1.,  0.],
        [ 1.,  2.,  1.,  1.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  1.,  0.,  0.,  0.]]),
 [(1, 3), (

In [661]:
v[(2,0)]

[(3, 0), (2, 1), (1, 0)]

In [ ]:
def _cases_vides(mat):
    cases=cases_vides()
    for k in cases:
        [a,b]=k
        mat[a][b]=0
    return mat
  
def initialisation_matrice():
    matrice = np.ones([7,7])
    matrice = _cases_vides(matrice)
    cases_un = [list(x) for x in np.argwhere(matrice == 1)]
    deux_r=random.choice(cases_un)
    i=deux_r[0]
    j=deux_r[1]

    matrice[i][j]=2

    return matrice

In [ ]:
matrice2 = initialisation_matrice()
vraideplacement(matrice2)

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap

colors = [(0.8, 0.8, 0.8), (0, 0, 1), (1, 0, 0)]  # R -> G -> B
n_bins = [3] 
cmap_name = 'ma_colormap'

#taille
size = np.array(matrice2.shape)
dpi = 10.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig = plt.figure(figsize = figsize, dpi = 30*dpi, facecolor = "white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon = False)

#affichage/couleur
im=plt.imshow(matrice2, interpolation = 'none', cmap =  LinearSegmentedColormap.from_list(
        cmap_name, colors))
plt.xticks([]), plt.yticks([])

#titre
plt.title("La propagation de la varicelle dans une classe de maternelle.")

#légende
grey_patch = mpatches.Patch(color='grey', label='les endroits vides de la classe')
black_patch = mpatches.Patch(color='red', label='les enfants malades')
white_patch = mpatches.Patch(color='blue', label='les enfants sains')

plt.legend(prop={'size': 4},handles=[black_patch, grey_patch, white_patch],bbox_to_anchor=(-0.5, 1.0, 0., 0))

#animation
import matplotlib.animation as animation


# Initialisation de la matrice
matrice2 = initialisation_matrice()

def update(*args):
    vraideplacement(matrice2)
    im.set_array(matrice2)
    return im,

ani = animation.FuncAnimation(fig, update, interval=1000)

plt.show()



In [ ]:
print(matrice2)